stages:


  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - src/models.py
    - src/dataset.py
    params:
    - MODEL_STRUCTURE
    - EPOCHS
    - BATCH_SIZE
    - IMG_SIZE
    - OPTIMIZER
    - LEARNING_RATE
    - SCHEDULER
    - CRITERION
    - FREEZE_LAYERS
    outs:
    - metrics
    - models

  inference:
    cmd: python src/inference.py
    deps:
      - src/inference.py
      - models/
      - data/test/
      - data/test_frames_keypoints.csv
    params:
      - ROOT_DIR
      - IMG_SIZE
    outs:
      - data/predictions


metrics:
- metrics/metrics.json
plots:
  - training loss:
      template: simple
      x: step
      y:
        metrics/plots/metrics/train/loss.tsv: loss
  - test loss:
      template: simple
      x: step
      y:
        metrics/plots/metrics/test/loss.tsv: loss

  - test pck:
      template: simple
      x: step
      y:
        metrics/plots/metrics/test/pck.tsv: pck
  # - test accuracy:
  #     template: simple
  #     x: step
  #     y:
  #       metrics/plots/metrics/test/accuracy.tsv: accuracy
