# * Model Choice
# Current choices: resnet18, resnet34, resnet50, resnet101, resnet152
MODEL_STRUCTURE: resnet18

# ? Hyperparameters
EPOCHS: 30
BATCH_SIZE: 16
IMG_SIZE : 224
# Current optimzer support: sgd, adam, adamw, rmsprop
OPTIMIZER: 'adam' 
LEARNING_RATE: 0.001
# Current scheduler support: None, 'constant', 'exponential'
SCHEDULER: constant
# Current criterion support: mse, cross-entropy
CRITERION: mse

